package Module;

public enum Outputs {
    WAIT_UNTIL_TIME_FOR_WRONG_PASSWORD_FINISH,
    WRONG_PASSWORD,
    USERNAME_DOESNT_EXIST,
    CURRENT_USER_LOGGED_IN_SUCCESSFULY,
    OPPONENT_USER_LOGGED_IN_SUCCESSFULY,
    USERNAME_SYNTAX_INVALID,
    USERNAME_ALREADY_EXIST,
    PASSWORD_NOT_STRONG_ENOUGH,
    EMAIL_NOT_ACCEPTABLE,
    CONFIRMATION_PASSWORD_DOESNT_MATCH,
    USER_CREATED_SUCCESSFULLY,
    GONE_FOR_SECURITY_QUESTION,
    USERNAME_CHANGED_SUCCESSFULLY,
    NICKNAME_CHANGED_SUCCESSFULLY,
    EMAIL_CHANGED_SUCCESSFULLY,
    NEW_PASSWORD_IS_THE_SAME,
    PASSWORD_CHANGED_SUCCESSFULLY,
    CANT_PLACE_CARD_HERE,
    PLAYER1_WON,
    PLAYER2_WON,
    DRAW,
    IN_TIME_LINE,

    ;

}
